export const initialMockItems = [
  {
    id: "mock-1",
    title: "Black Apple AirPods Pro",
    type: "found",
    category: "electronics",
    description: "Found on a table near the window on the 3rd floor of the main library. The case has a small scratch on the back hinge. Inside, the right AirPod has a minor scuff.",
    location: "Main Library 3rd Floor",
    date: "2026-06-01",
    contactName: "Alex Mercer",
    contactEmail: "alex.mercer@university.edu",
    contactPhone: "555-0192",
    image: "https://images.unsplash.com/photo-1588449668338-d1517689fc7f?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "What is the name engraved on the case (if any) or color of the internal lining?",
    createdAt: "2026-06-01T14:30:00.000Z"
  },
  {
    id: "mock-2",
    title: "University Student ID - Sarah Jenkins",
    type: "found",
    category: "documents",
    description: "Found a student ID card near the cash register of the Union Cafeteria. Card number ends in 4829. Photo is of a female student with brown hair.",
    location: "Student Union Cafeteria",
    date: "2026-06-02",
    contactName: "Chef David",
    contactEmail: "d.kovac@university.edu",
    contactPhone: "555-0144",
    image: "https://images.unsplash.com/photo-1598257006458-087169a1f08d?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "What is the middle name printed on the student ID card?",
    createdAt: "2026-06-02T08:15:00.000Z"
  },
  {
    id: "mock-3",
    title: "Lost: Blue Hydro Flask Water Bottle",
    type: "lost",
    category: "accessories",
    description: "I lost my blue 32oz Hydro Flask with a flex straw cap. It has a stickers of the university logo and a sticker of a retro sunset. Last seen in the Science Building Room 204.",
    location: "Science Building Room 204",
    date: "2026-05-30",
    contactName: "Jessica Chen",
    contactEmail: "jessica.chen@student.edu",
    contactPhone: "555-0188",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "",
    createdAt: "2026-05-30T10:45:00.000Z"
  },
  {
    id: "mock-4",
    title: "TI-84 Plus CE Graphing Calculator",
    type: "found",
    category: "electronics",
    description: "Found a black TI-84 Plus CE calculator sitting in the back row of the Chemistry Lecture Hall. It functions perfectly and has a battery level of about 50%.",
    location: "Chemistry Lecture Hall",
    date: "2026-05-31",
    contactName: "Prof. Marcus Vance",
    contactEmail: "m.vance@university.edu",
    contactPhone: "555-0105",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "What name or initials are written in permanent marker inside the slide cover?",
    createdAt: "2026-05-31T16:20:00.000Z"
  },
  {
    id: "mock-5",
    title: "Lost: Organic Chemistry Textbook (Wade, 9th Ed)",
    type: "lost",
    category: "books",
    description: "Lost my Organic Chemistry textbook. It has a slight water damage on the bottom right corner of the pages. Left it in the library study lounge on the 2nd floor.",
    location: "Main Library 2nd Floor",
    date: "2026-06-01",
    contactName: "Ryan Peterson",
    contactEmail: "ryan.p@student.edu",
    contactPhone: "555-0132",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "",
    createdAt: "2026-06-01T09:00:00.000Z"
  },
  {
    id: "mock-6",
    title: "Set of Keys on Red Lanyard",
    type: "found",
    category: "keys",
    description: "Found a set of keys with a Honda key fob and three house keys on a red university lanyard. Found near the outdoor basketball courts.",
    location: "Campus Recreation Center",
    date: "2026-06-02",
    contactName: "Coach Miller",
    contactEmail: "miller.sports@university.edu",
    contactPhone: "555-0177",
    image: "https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=600&q=80",
    status: "active",
    secretQuestion: "What keychains besides the key fob are attached to the ring, and how many house keys are there exactly?",
    createdAt: "2026-06-02T10:10:00.000Z"
  },
  {
    id: "mock-7",
    title: "Grey University Hoodie",
    type: "found",
    category: "clothing",
    description: "Found a grey pullover university hoodie size L draped over a chair in the Computer Science Lab on the 1st floor.",
    location: "Computer Science Lab",
    date: "2026-05-29",
    contactName: "T.A. Liam Wood",
    contactEmail: "l.wood@university.edu",
    contactPhone: "555-0121",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
    status: "resolved",
    secretQuestion: "Are there any specific stains, tears, or writing on the tag?",
    createdAt: "2026-05-29T11:00:00.000Z"
  }
];
